### ISSUE TITLE
Create hydrator repo

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-stdlib#1]
Hi,

Could someone create the zend-hydrator repo please? :)

Thanks!

**Comment by gianarb** [comment]
:+1: @weierophinney :) Feedback? :)

**Comment by gianarb** [comment]
Another question.
How can we remove service-manager dependency? :)

**Comment by sandrokeil** [comment]
+1 for zend-hydrator repo. @gianarb Hmm and what is with the plugin manager? May be we need than [something like this](https://github.com/sandrokeil/EasyConfig/blob/master/docs/ServiceManagerConfig.md "") for easy configuration.

**Comment by gianarb** [comment]
@sandrokeil I do not know what I need :) 
I know that I wish I choice when I download all component because I'm in a very big and power project and when I would use only a simple hydrator  :P

**Comment by RalfEggert** [comment]
When will the Zend\Hydrator repo be introduced?

**Comment by weierophinney** [comment]
Created today: https://github.com/zendframework/zend-hydrator

Next step is to go through zend-stdlib and:

- Add a dependency on zend-hydrator
- Have each hydrator-related class extend from the equivalent zend-hydrator class
- Mark each hydrator-related class as deprecated

Once that's done, we can release a 2.6 version of zend-stdlib.

Additionally, we'll need to update the next minor version of zend-mvc to provide hydrator manager factories for each of zend-stdlib and zend-hydrator, to allow folks to migrate between the two.

**Comment by weierophinney** [comment]
Oh, and we'll have to update zend-db as well (HydratingResultSet).

**Comment by Maks3w** [comment]
- [ ] Add deprecations to current hydrator classes.

**Comment by weierophinney** [comment]
@Maks3w I already noted that in my above comments. ;-)

**Comment by weierophinney** [comment]
I've created #20 to address the deprecation; closing this for now, as the repository has been created as requested.
