### ISSUE TITLE
move NamingStrategy to inside Stategy

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-stdlib#14]
I think NamingStrategy classes can be moved to inside Strategy to collect the strategies. To avoid bc break, we can made old NamingStrategy classes extends Strategy\NamingStrategy\StrategyName.

Any thoughts?

**Comment by gianarb** [comment]
Maybe we can build it for ZF3.. Double class is worse respect a ugly path IMO

**Comment by samsonasik** [comment]
@gianarb Ok, I've created PR #15 for it ;)

**Comment by Maks3w** [comment]
I don't see where is the relation between Strategy and NamingStrategy more far the repetition of characters in the name.

Both interfaces are independent. StrategyInterface vs NamingStrategyInterface

**Comment by Maks3w** [comment]
Both subcomponents has different responsabilities.

NamingStrategy receive strings and return strings. This component only want to standarize a name.
StrategyInterface receives any and returns any. This component convert between different types extract from type A to type B and viceversa

**Comment by samsonasik** [comment]
While they have different responsibility, they still "a strategy", thats why it good to be collected to 1 directory.

**Comment by Maks3w** [comment]
That is like to say all interfaces in the same directory. Components are grouped by semantics not by nature.

**Comment by samsonasik** [comment]
that was different terminology

Warm regards,

Abdul Malik Ikhsan

Pada 25 Jul 2015, pukul 16.39, Maks3w <notifications@github.com> menulis:
