### ISSUE TITLE
PHP 7 compatability issue

### ISSUE THREAD

**Issue by dvc** [zendframework/zend-stdlib#16]
$ php bin/php7cc.php ../some-symfony-project

File: ../some-symfony-project/vendor/zendframework/zend-stdlib/src/Hydrator/ClassMethods.php
Line 220. Indirect variable, property or method access: $object->{$this->hydrationMethodsCache[$propertyFqn]}($this->hydrateValue($property, $value, $data));

File: ../some-symfony-project/vendor/zendframework/zend-stdlib/src/CallbackHandler.php
Line 122. Function argument(s) returned by "func_get_args" might have been modified: func_get_args();

**Comment by weierophinney** [comment]
Can you please provide a unit test showing the functionality being exercised that exhibits this behavior? RIght now, I do not have enough information to create a test case, and our current suite of tests is running perfectly against PHP 7.

**Comment by dvc** [comment]
I`m sorry, it is an analizer paranoia, not a bug. My mistake :(
This issue should be closed
