### ISSUE TITLE
php 5.5 dependency

### ISSUE THREAD

**Issue by axhm3a** [zendframework/zend-stdlib#17]
Hello,

is the dep on php >=5.5 necessary?

greetings,

daniel

**Comment by Maks3w** [comment]
There is no guarantee of work on lower versions.

**Comment by manuakasam** [comment]
@axhm3a just as a follow up:
Version 2.4 of any zend-component only requires `php: >=5.3.23` so you'll be safe to use this for quite a while. However future development should always be done on the more current versions of PHP available. Even PHP 5.5 will only be supported for roughly one more year (from PHP itself). See http://php.net/supported-versions.php for more information.
