### ISSUE TITLE
php version issue starting at 2.5.2

### ISSUE THREAD

**Issue by cridoret** [zendframework/zend-stdlib#28]
The required php version went from ">=5.3.23" in 2.5.1 to ">=5.5" in 2.5.2. Shouldn't that change have been done in 2.5.0 instead of in a patch version?

**Comment by weierophinney** [comment]
We stopped testing against 5.3 and 5.4 for the 2.5 release, by forgot to
update the composer requirement. The intention was to only support 5.5,
however, and we updated all libraries in immediate patch versions to
reflect the intention.
