### ISSUE TITLE
RequestInterface missing getPost

### ISSUE THREAD

**Issue by boesing** [zendframework/zend-stdlib#29]
As of zend-mvc [Zend\Mvc\Controller\AbstractController](https://github.com/zendframework/zend-mvc/blob/master/src/Controller/AbstractController.php), you'll get the RequestInterface as a response of AbstractController::getRequest(). 

Thus will lead to issues on resolving getPost() in Autocompletions. IMHO, getPost method should be required to any RequestInterface implementing class.

_Example_
```
class DummyController extends \Zend\Mvc\Controller\AbstractController 
{
    public function dummyAction() 
    {
        $request = $this->getRequest();
        $postValues = $request->getPost();
    }    
}
```

The getPost method will work, since \Zend\Http\Request implements it. But Autocompletion wont resolve this, since the return value is RequestInterface.

**Comment by weierophinney** [comment]
This is intentional. `Zend\Stdlib\RequestInterface` is a general purpose request abstraction, and is used as a base for both the HTTP variant as well as those used in zend-mail and zend-console.

If you want IDE autocompletion, you can always put typehints as comments above the variable:

```php
/* @var \Zend\Http\PhpEnvironment\Request */
$request = $this->getRequest();
```
