### ISSUE TITLE
Missing multibyte extension in composer.json

### ISSUE THREAD

**Issue by danrot** [zendframework/zend-stdlib#53]
As you are using the multibyte extension in the string wrapper, this should also be mentioned in the composer.json file, like described in [this blog post](https://coderwall.com/p/deyqua/how-to-use-mbstring-on-heroku-php). I am running a project on heroku using this library, and I have to add this extension now to my project, although it would belong here.

Is there any reason not to add this? Otherwise I would provide a PR.

**Comment by weierophinney** [comment]
It can be added under the `suggest` section, but should not be under the `require` section. The reason is because all functionality in zend-stdlib is opt-in, and many components are using only `ArrayUtils` or the various SPL extensions.

**Comment by danrot** [comment]
Ok, we are using the zend search library, so should it be there in the require section?

**Comment by weierophinney** [comment]
@danrot Add it to the `require` section of your application; since your application requires it, that's the place to put it.

**Comment by Ocramius** [comment]
@danfinnie should be added to https://github.com/zendframework/ZendSearch, although that library is not maintained

**Comment by danrot** [comment]
@Ocramius Ok, any chance to add it there although it is not maintained? And I am just curious, but do you know any maintained alternative?

**Comment by Ocramius** [comment]
Not aware of any

**Comment by danrot** [comment]
Ok, then I gonna close this issue... Maybe I'll try to add that later to zend search, if that is ok, and there is any chance of anybody merging it.
