### ISSUE TITLE
GLOB_BRACE support on Alpine and others musl-based distros

### ISSUE THREAD

**Issue by cusspvz** [zendframework/zend-stdlib#58]
Seems that Alpine [doesn't support](https://github.com/magento/magento2/issues/2130#issuecomment-208809834) `GLOB_BRACE` since it is using **musl libc** instead of **GNU libc**. 

This module is affecting some installations since it depends on it. Is there a chance to work around it?

**Comment by Ocramius** [comment]
> Is there a chance to work around it?

Seems like calling `glob()` multiple times and then doing an `array_merge()` is the solution for those systems. We cannot support it ourselves though, as we'd have to rewrite a `glob` implementation in userland then :(

**Comment by cusspvz** [comment]
@Ocramius thanks for your super fast response!!

Well, seems you [already have a fallback](https://github.com/zendframework/zend-stdlib/blob/master/src/Glob.php#L39-L46), but in fact seems that the system isn't complaining about the implementation but instead about the [non declarated use](https://github.com/zendframework/zend-stdlib/blob/master/src/Glob.php#L64).

```
  [Exception]
  Notice: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' in /magento/vendor/zendframework/zend-stdlib/src/Glob.php on line 64
```

Shouldn't this have a `defined('GLOB_BRACE')` check?

**Comment by Ocramius** [comment]
@cusspvz that should be quite easy to fix, yes (@DASPRiD built some workarounds before 2.0 to support old UNIX systems that didn't have `GLOB_BRACE`). Can you attempt a fix?

Also, remember to always link absolute code reference: using just `master` causes links to be broken on long term (due to code moving around)

**Comment by cusspvz** [comment]
> Also, remember to always link absolute code reference: using just master causes links to be broken on long term (due to code moving around)

@Ocramius can you please explain what you meant here? Didn't understood, sorry.

**Comment by Ocramius** [comment]
@cusspvz look at the links in your comment above: I modified them to point at a specific SHA1 of the repo

**Comment by cusspvz** [comment]
Ohh, I got it now! Thanks!!
