### ISSUE TITLE
Error by use Expressive 2.0.1 with Skeleton Application

### ISSUE THREAD

**Issue by mano87** [zendframework/zend-stdlib#72]
Hello,
directly after the installation of the Skeleton Expressive Application I get the following error:

> [10-Mar-2017 09:24:30 UTC] PHP Fatal error:  Class Zend\Stdlib\PriorityList contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Countable::) in D:\webworkspace\projects\zend-skeleton\vendor\zendframework\zend-stdlib\src\PriorityList.php on line 15

Why?

**Comment by froschdesign** [comment]
@mano87 
Please report this error on the [`zend-expressive-skeleton` issue tracker](https://github.com/zendframework/zend-expressive-skeleton/issues). Thanks!
