### ISSUE TITLE
Zend\Stdlib\ErrorHandler breaks custom error handlers

### ISSUE THREAD

**Issue by unhawkable** [zendframework/zend-stdlib#78]
Cross-referenced an already submitted issue, as the bug in php has still not been fixed and the issue is still relevant: zendframework/zendframework#7497

**Comment by weierophinney** [comment]
And, as noted: this is a PHP bug, not a framework one. If we change how `ErrorHandler` calls `set_error_handler()`, we potentially end up triggering the handler for error levels it should not handle.
