### ISSUE TITLE
Broken test with PHP 7.2

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-stdlib#82]
Detected by Fedora QA with 7.2.0RC4
https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-stdlib?collection=f28

`     Parameter must be an array or an object that implements Countable`

Possible fix in PR #81 but as I don't want to go bikeshedding, please fix it yourself.

**Comment by froschdesign** [comment]
Fixed with 3921c941891a05189686886dbc4dadfbba089156
