### ISSUE TITLE
Provide support for PHP 7.2

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-stdlib#88]
We need to test against 7.2, and fix any errors observed.

Additionally, we can:

- Remove support for HHVM
- Add support for PHP 7.1

**Comment by webimpress** [comment]
@weierophinney Everything here is done already on develop, see: https://github.com/zendframework/zend-stdlib/compare/develop

**Comment by weierophinney** [comment]
Resolved with release 3.2.0.
